# Railway deployment configuration
# This file is read by Railway to configure deployment

# Build settings
[build]
command = "npm run build"

# Start command
[start]
command = "npm start"

# Environment variables needed:
# REDIS_URL=your_redis_url
# REDIS_TOKEN=your_redis_token  
# JWT_SECRET=your_jwt_secret

# Health check endpoint
[health]
endpoint = "/"
